version: '3.1'

services:

  primary-db:
    image: primary-db
    restart: always
    ports:
      - "5432:5432"
      
  failover-db:
    image: failover-db
    restart: always
    ports:
      - "5433:5432"